name: Build and Push Docker Image to Alibaba Cloud ACR
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
    - name: Configure Docker DNS
      run: |
        echo '{"dns": ["8.8.8.8", "223.5.5.5"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Alibaba Cloud ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login \
          --username=${{ secrets.ACR_USERNAME }} \
          ${{ secrets.ACR_REGISTRY }} --password-stdin 

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/${{ secrets.ACR_REPO }}:latest .

    - name: Push Docker Image to ACR
      run: |
        docker push ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/${{ secrets.ACR_REPO }}:latest
